"use client"

import { useState } from "react"
import { DetailPane } from "@/components/features/DetailPane"
import { Button } from "@/components/ui/Button"

/**
 * Demo page for the DetailPane component
 * 
 * This page demonstrates all features of the DetailPane component:
 * - Editable text area with auto-save
 * - Read-only mode
 * - Code-derived content with monospace font
 * - Utility actions (copy, export, regenerate)
 * - Theme-appropriate styling
 */
export default function DetailPaneDemoPage() {
     const [content, setContent] = useState("This is editable content. Try editing it and clicking outside the text area to auto-save.")
     const [savedContent, setSavedContent] = useState("")
     const [mode, setMode] = useState<"edit" | "readonly">("edit")
     const [isCodeDerived, setIsCodeDerived] = useState(false)

     const handleSave = (newContent: string) => {
          setSavedContent(newContent)
          console.log("Content saved:", newContent)
     }

     const handleExport = () => {
          console.log("Exporting content:", content)
          alert("Content exported! Check console for details.")
     }

     const handleRegenerate = () => {
          const newContent = `Regenerated content at ${new Date().toLocaleTimeString()}\n\nThis is fresh content generated by the system.`
          setContent(newContent)
          console.log("Content regenerated")
     }

     const codeExample = `function calculateSum(a: number, b: number): number {
    return a + b;
}

const result = calculateSum(5, 10);
console.log(result); // Output: 15`

     const regularExample = `This is a regular text example.

It demonstrates the DetailPane component with:
- Multiple paragraphs
- Clear separation from UI chrome
- Theme-appropriate styling
- Comfortable reading experience

The component follows all design requirements for a professional, developer-focused interface.`

     return (
          <div className="min-h-screen bg-bg-app p-8">
               <div className="max-w-7xl mx-auto space-y-8">
                    {/* Header */}
                    <div>
                         <h1 className="text-lg font-semibold text-text-primary mb-2">
                              Detail Pane Component Demo
                         </h1>
                         <p className="text-sm text-text-secondary">
                              Demonstrating the editor-like preview area with all features
                         </p>
                    </div>

                    {/* Controls */}
                    <div className="bg-bg-panel border border-border-subtle rounded-lg p-lg space-y-4">
                         <h2 className="text-md font-semibold text-text-primary">Controls</h2>

                         <div className="flex flex-wrap gap-4">
                              <Button
                                   variant={mode === "edit" ? "primary" : "secondary"}
                                   onClick={() => setMode("edit")}
                              >
                                   Edit Mode
                              </Button>
                              <Button
                                   variant={mode === "readonly" ? "primary" : "secondary"}
                                   onClick={() => setMode("readonly")}
                              >
                                   Read-Only Mode
                              </Button>
                              <Button
                                   variant={isCodeDerived ? "primary" : "secondary"}
                                   onClick={() => setIsCodeDerived(!isCodeDerived)}
                              >
                                   {isCodeDerived ? "Monospace Font" : "Regular Font"}
                              </Button>
                              <Button
                                   variant="ghost"
                                   onClick={() => setContent(codeExample)}
                              >
                                   Load Code Example
                              </Button>
                              <Button
                                   variant="ghost"
                                   onClick={() => setContent(regularExample)}
                              >
                                   Load Text Example
                              </Button>
                              <Button
                                   variant="ghost"
                                   onClick={() => setContent("")}
                              >
                                   Clear Content
                              </Button>
                         </div>

                         {savedContent && (
                              <div className="mt-4 p-4 bg-bg-elevated border border-border-subtle rounded">
                                   <p className="text-sm text-text-secondary mb-2">Last saved content:</p>
                                   <p className="text-sm text-text-primary font-mono">{savedContent.substring(0, 100)}...</p>
                              </div>
                         )}
                    </div>

                    {/* Demo Grid */}
                    <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
                         {/* Full-featured example */}
                         <div className="space-y-4">
                              <h2 className="text-md font-semibold text-text-primary">
                                   Full-Featured Detail Pane
                              </h2>
                              <div className="h-[500px]">
                                   <DetailPane
                                        content={content}
                                        onContentChange={setContent}
                                        onSave={handleSave}
                                        onExport={handleExport}
                                        onRegenerate={handleRegenerate}
                                        readOnly={mode === "readonly"}
                                        isCodeDerived={isCodeDerived}
                                        title="Content Editor"
                                        placeholder="Start typing or load an example..."
                                   />
                              </div>
                         </div>

                         {/* Minimal example */}
                         <div className="space-y-4">
                              <h2 className="text-md font-semibold text-text-primary">
                                   Minimal Detail Pane
                              </h2>
                              <div className="h-[500px]">
                                   <DetailPane
                                        content="This is a minimal DetailPane with no title or utility actions. It still provides the core editing experience with auto-save functionality."
                                        onSave={(content) => console.log("Minimal pane saved:", content)}
                                   />
                              </div>
                         </div>

                         {/* Code-derived example */}
                         <div className="space-y-4">
                              <h2 className="text-md font-semibold text-text-primary">
                                   Code-Derived Content
                              </h2>
                              <div className="h-[500px]">
                                   <DetailPane
                                        content={codeExample}
                                        isCodeDerived={true}
                                        readOnly={true}
                                        title="Code Preview"
                                   />
                              </div>
                         </div>

                         {/* Empty state example */}
                         <div className="space-y-4">
                              <h2 className="text-md font-semibold text-text-primary">
                                   Empty State
                              </h2>
                              <div className="h-[500px]">
                                   <DetailPane
                                        content=""
                                        title="Empty Content"
                                        placeholder="No content available. Click 'Regenerate' to create new content."
                                        onRegenerate={() => setContent("Newly generated content!")}
                                   />
                              </div>
                         </div>
                    </div>

                    {/* Requirements Checklist */}
                    <div className="bg-bg-panel border border-border-subtle rounded-lg p-lg">
                         <h2 className="text-md font-semibold text-text-primary mb-4">
                              Requirements Checklist
                         </h2>
                         <ul className="space-y-2 text-sm text-text-secondary">
                              <li className="flex items-start gap-2">
                                   <span className="text-accent-neutral">✓</span>
                                   <span><strong>Requirement 12.1:</strong> Editor-like preview area with 24px padding</span>
                              </li>
                              <li className="flex items-start gap-2">
                                   <span className="text-accent-neutral">✓</span>
                                   <span><strong>Requirement 12.2:</strong> Clear separation from UI chrome</span>
                              </li>
                              <li className="flex items-start gap-2">
                                   <span className="text-accent-neutral">✓</span>
                                   <span><strong>Requirement 12.3:</strong> Editable text area with auto-save on blur</span>
                              </li>
                              <li className="flex items-start gap-2">
                                   <span className="text-accent-neutral">✓</span>
                                   <span><strong>Requirement 12.4:</strong> Monospace font for code-derived content</span>
                              </li>
                              <li className="flex items-start gap-2">
                                   <span className="text-accent-neutral">✓</span>
                                   <span>Utility actions: Copy, Export, Regenerate</span>
                              </li>
                              <li className="flex items-start gap-2">
                                   <span className="text-accent-neutral">✓</span>
                                   <span>Theme-appropriate styling with design tokens</span>
                              </li>
                              <li className="flex items-start gap-2">
                                   <span className="text-accent-neutral">✓</span>
                                   <span>Keyboard accessibility with focus indicators</span>
                              </li>
                              <li className="flex items-start gap-2">
                                   <span className="text-accent-neutral">✓</span>
                                   <span>ARIA labels for screen readers</span>
                              </li>
                         </ul>
                    </div>
               </div>
          </div>
     )
}
